In [2]:
import sys 
from pathlib import Path
sys.path.insert(0,str(Path().resolve().parent))
import pandas as pd

In [3]:
from src.utils.db import connect_to_db
engine=connect_to_db()

parameters of DATABASE sucessfuly loaded
connection sucessful

In [4]:
query_f6= """ SELECT * FROM bronze.f6_1_ied_installations
WHERE "CountryName"='Belgium' """

In [5]:
f6_be=pd.read_sql(query_f6,engine)
f6_be.head()

,PublicationDate,CountryName,reportingYear,parent_facilityInspireId,EPRTRAnnexIMainActivity,InstallationInspireId,installationName,installationNameConfidentialityReason,City_of_Facility,Longitude,...,permitGranted,dateOfGranting,permitReconsidered,permitUpdated,dateOfLastUpdate,permitURL,RelevantChapter,BATConclusion,BATAEL,BATAELStricterCondition
0,2026/02/13,Belgium,2023,BE.WA/297010000.FACILITY,7(a)(ii),BE.WA/297010100.INSTALLATION,Elevage de porcs,NaN,Comines-Warneton,3.001007,...,Yes,2011-01-01,No,Yes,2017-03-31,http://environnement.wallonie.be/cgi/dgrne/aer...,NaN,IRPP,NaN,NaN
1,2026/02/13,Belgium,2023,BE.WA/099010000.FACILITY,8(b)(ii),BE.WA/099010100.INSTALLATION,Combustion,NaN,Leuze-En-Hainaut,3.632182,...,Yes,2002-01-01,No,No,1900-01-01,http://environnement.wallonie.be/cgi/dgrne/aer...,NaN,FDM,NaN,NaN
2,2026/02/13,Belgium,2023,BE.WA/047010000.FACILITY,4(a)(viii),BE.WA/047010100.INSTALLATION,Combustion,NaN,Feluy,4.223438,...,Yes,2021-12-21,No,No,1900-01-01,http://environnement.wallonie.be/cgi/dgrne/aer...,NaN,WGC,NaN,NaN
3,2026/02/13,Belgium,2023,BE.WA/240010000.FACILITY,5(a),BE.WA/240010100.INSTALLATION,Traitement biologique de terres polluées par h...,NaN,NaN,3.868725,...,Yes,2009-01-01,No,No,1900-01-01,http://environnement.wallonie.be/cgi/dgrne/aer...,NaN,WT,NaN,NaN
4,2026/02/13,Belgium,2023,BE.WA/010010000.FACILITY,6(b),BE.WA/010010400.INSTALLATION,Coïncinération,NaN,Vielsalm,5.956051,...,Yes,2017-07-13,No,No,1900-01-01,http://environnement.wallonie.be/cgi/dgrne/aer...,NaN,WBP,NaN,NaN

In [6]:
f6_be.info()

<class 'pandas.DataFrame'>
RangeIndex: 20129 entries, 0 to 20128
Data columns (total 31 columns):
 #   Column                                 Non-Null Count  Dtype
---  ------                                 --------------  -----
 0   PublicationDate                        20129 non-null  str
 1   CountryName                            20129 non-null  str
 2   reportingYear                          20129 non-null  int64
 3   parent_facilityInspireId               20129 non-null  str
 4   EPRTRAnnexIMainActivity                19136 non-null  str
 5   InstallationInspireId                  20129 non-null  str
 6   installationName                       20129 non-null  str
 7   installationNameConfidentialityReason  7767 non-null   str
 8   City_of_Facility                       19924 non-null  str
 9   Longitude                              20129 non-null  float64
 10  Latitude                               20129 non-null  float64
 11  addressConfidentialityReason           0 non-null      object
 12  installationStatus                     20129 non-null  str
 13  IEDAnnexIMainActivity                  20129 non-null  str
 14  IEDMainActivityName                    20129 non-null  str
 15  baselineReportIndicator                20129 non-null  str
 16  siteVisitNumber                        20129 non-null  float64
 17  siteVisitURL                           18316 non-null  str
 18  dateOfStartOfOperation                 4782 non-null   str
 19  publicEmissionMonitoring               18321 non-null  str
 20  publicEmissionMonitoringURL            18321 non-null  str
 21  permitGranted                          20129 non-null  str
 22  dateOfGranting                         20129 non-null  str
 23  permitReconsidered                     20129 non-null  str
 24  permitUpdated                          20129 non-null  str
 25  dateOfLastUpdate                       20129 non-null  str
 26  permitURL                              20097 non-null  str
 27  RelevantChapter                        3059 non-null   str
 28  BATConclusion                          20114 non-null  str
 29  BATAEL                                 53 non-null     str
 30  BATAELStricterCondition                4 non-null      str
dtypes: float64(3), int64(1), object(1), str(26)
memory usage: 4.8+ MB

In [7]:
f6_be.isnull().sum()

PublicationDate                              0
CountryName                                  0
reportingYear                                0
parent_facilityInspireId                     0
EPRTRAnnexIMainActivity                    993
InstallationInspireId                        0
installationName                             0
installationNameConfidentialityReason    12362
City_of_Facility                           205
Longitude                                    0
Latitude                                     0
addressConfidentialityReason             20129
installationStatus                           0
IEDAnnexIMainActivity                        0
IEDMainActivityName                          0
baselineReportIndicator                      0
siteVisitNumber                              0
siteVisitURL                              1813
dateOfStartOfOperation                   15347
publicEmissionMonitoring                  1808
publicEmissionMonitoringURL               1808
permitGranted                                0
dateOfGranting                               0
permitReconsidered                           0
permitUpdated                                0
dateOfLastUpdate                             0
permitURL                                   32
RelevantChapter                          17070
BATConclusion                               15
BATAEL                                   20076
BATAELStricterCondition                  20125
dtype: int64

In [8]:
f6_be.columns

Index(['PublicationDate', 'CountryName', 'reportingYear',
       'parent_facilityInspireId', 'EPRTRAnnexIMainActivity',
       'InstallationInspireId', 'installationName',
       'installationNameConfidentialityReason', 'City_of_Facility',
       'Longitude', 'Latitude', 'addressConfidentialityReason',
       'installationStatus', 'IEDAnnexIMainActivity', 'IEDMainActivityName',
       'baselineReportIndicator', 'siteVisitNumber', 'siteVisitURL',
       'dateOfStartOfOperation', 'publicEmissionMonitoring',
       'publicEmissionMonitoringURL', 'permitGranted', 'dateOfGranting',
       'permitReconsidered', 'permitUpdated', 'dateOfLastUpdate', 'permitURL',
       'RelevantChapter', 'BATConclusion', 'BATAEL',
       'BATAELStricterCondition'],
      dtype='str')

In [9]:
f6_1_col_to_keep=['reportingYear',
       'parent_facilityInspireId',
       'InstallationInspireId',
       'City_of_Facility',
       'Longitude', 'Latitude',
       'installationStatus']

In [10]:
f6_be=f6_be[f6_1_col_to_keep]

In [11]:
f6_be['installationStatus'].value_counts()

installationStatus
functional        19305
notRegulated        351
decommissioned      260
disused             213
Name: count, dtype: int64

In [12]:
f6_be.groupby(['InstallationInspireId', 'reportingYear']).size().value_counts()

1     19073
2        72
18       24
6        15
3        13
5        12
4         9
22        3
23        3
9         3
14        3
10        3
7         3
Name: count, dtype: int64

In [13]:
dupes = f6_be.groupby(['InstallationInspireId', 'reportingYear']).size()
example_id = dupes[dupes == 18].index[0]
f6_be[(f6_be['InstallationInspireId'] == example_id[0]) & 
      (f6_be['reportingYear'] == example_id[1])][f6_1_col_to_keep]

,reportingYear,parent_facilityInspireId,InstallationInspireId,City_of_Facility,Longitude,Latitude,installationStatus
3153,2022,BE.WA/049010000.FACILITY,BE.WA/000002135.INSTALLATION,Jemeppe-Sur-Sambre,4.662693,50.447224,notRegulated
3154,2022,BE.WA/049010000.FACILITY,BE.WA/000002135.INSTALLATION,Jemeppe-Sur-Sambre,4.662693,50.447224,notRegulated
3155,2022,BE.WA/049010000.FACILITY,BE.WA/000002135.INSTALLATION,Jemeppe-Sur-Sambre,4.662693,50.447224,notRegulated
3156,2022,BE.WA/049010000.FACILITY,BE.WA/000002135.INSTALLATION,Jemeppe-Sur-Sambre,4.662693,50.447224,notRegulated
3157,2022,BE.WA/049010000.FACILITY,BE.WA/000002135.INSTALLATION,Jemeppe-Sur-Sambre,4.662693,50.447224,notRegulated
3158,2022,BE.WA/049010000.FACILITY,BE.WA/000002135.INSTALLATION,Jemeppe-Sur-Sambre,4.662693,50.447224,notRegulated
3159,2022,BE.WA/049010000.FACILITY,BE.WA/000002135.INSTALLATION,Jemeppe-Sur-Sambre,4.662693,50.447224,notRegulated
3160,2022,BE.WA/049010000.FACILITY,BE.WA/000002135.INSTALLATION,Jemeppe-Sur-Sambre,4.662693,50.447224,notRegulated
3161,2022,BE.WA/049010000.FACILITY,BE.WA/000002135.INSTALLATION,Jemeppe-Sur-Sambre,4.662693,50.447224,notRegulated
3162,2022,BE.WA/049010000.FACILITY,BE.WA/000002135.INSTALLATION,Jemeppe-Sur-Sambre,4.662693,50.447224,notRegulated
3163,2022,BE.WA/049010000.FACILITY,BE.WA/000002135.INSTALLATION,Jemeppe-Sur-Sambre,4.662693,50.447224,notRegulated
3164,2022,BE.WA/049010000.FACILITY,BE.WA/000002135.INSTALLATION,Jemeppe-Sur-Sambre,4.662693,50.447224,notRegulated
3165,2022,BE.WA/049010000.FACILITY,BE.WA/000002135.INSTALLATION,Jemeppe-Sur-Sambre,4.662693,50.447224,notRegulated
3166,2022,BE.WA/049010000.FACILITY,BE.WA/000002135.INSTALLATION,Jemeppe-Sur-Sambre,4.662693,50.447224,notRegulated
3167,2022,BE.WA/049010000.FACILITY,BE.WA/000002135.INSTALLATION,Jemeppe-Sur-Sambre,4.662693,50.447224,notRegulated
3168,2022,BE.WA/049010000.FACILITY,BE.WA/000002135.INSTALLATION,Jemeppe-Sur-Sambre,4.662693,50.447224,notRegulated
3169,2022,BE.WA/049010000.FACILITY,BE.WA/000002135.INSTALLATION,Jemeppe-Sur-Sambre,4.662693,50.447224,notRegulated
4012,2022,BE.WA/049010000.FACILITY,BE.WA/000002135.INSTALLATION,Jemeppe-Sur-Sambre,4.662693,50.447224,notRegulated

**diagnostique**: ces 18 lignes sont strictement identiques sur toutes tes colonnes sélectionnées. Ce sont des vrais doublons source, pas des cas métier différents.
solution envisagée:
drop_duplicates() après le filtre functional.

**transform_f6()** aura cette logique dans l'ordre :

1)Filtre Belgium -directement dans la query

2)Filtre installationStatus == 'functional'directement dans la query

3)Sélection des colonnes

4)drop_duplicates()

5)Normalize text + lowercase colonnes

In [14]:
query_f6_be_functionnal="""SELECT * FROM bronze.f6_1_ied_installations
WHERE "CountryName"='Belgium' AND "installationStatus"='functional'

"""

In [15]:
f6_be_functional=pd.read_sql(query_f6_be_functionnal,con=engine)

In [16]:
f6_1_col_to_keep=['reportingYear',
       'parent_facilityInspireId',
       'InstallationInspireId',
       'City_of_Facility',
       'Longitude', 'Latitude',
       ]

In [17]:
f6_be_functional=f6_be_functional[f6_1_col_to_keep].copy()

In [18]:
f6_be_functional=f6_be_functional.drop_duplicates()

In [19]:
f6_be_functional.head()

,reportingYear,parent_facilityInspireId,InstallationInspireId,City_of_Facility,Longitude,Latitude
0,2023,BE.WA/297010000.FACILITY,BE.WA/297010100.INSTALLATION,Comines-Warneton,3.001007,50.802185
1,2023,BE.WA/099010000.FACILITY,BE.WA/099010100.INSTALLATION,Leuze-En-Hainaut,3.632182,50.604042
2,2023,BE.WA/240010000.FACILITY,BE.WA/240010100.INSTALLATION,NaN,3.868725,50.458390
3,2023,BE.WA/010010000.FACILITY,BE.WA/010010400.INSTALLATION,Vielsalm,5.956051,50.291027
4,2021,BE.WA/130010000.FACILITY,BE.WA/130010100.INSTALLATION,Mouscron,3.251511,50.745190

In [20]:
f6_be_functional.isnull().sum()

reportingYear                 0
parent_facilityInspireId      0
InstallationInspireId         0
City_of_Facility            157
Longitude                     0
Latitude                      0
dtype: int64

In [21]:
f6_be_functional.info()

<class 'pandas.DataFrame'>
Index: 18547 entries, 0 to 19304
Data columns (total 6 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   reportingYear             18547 non-null  int64
 1   parent_facilityInspireId  18547 non-null  str
 2   InstallationInspireId     18547 non-null  str
 3   City_of_Facility          18390 non-null  str
 4   Longitude                 18547 non-null  float64
 5   Latitude                  18547 non-null  float64
dtypes: float64(2), int64(1), str(3)
memory usage: 1014.3 KB

In [22]:
f6_be_functional=f6_be_functional.rename(str.lower, axis='columns')

In [23]:
def normalize_text(x):
    if pd.isna(x):
        return None
    x = str(x).lower().strip()
    for ch in ["-", "/", "(", ")", ",", ".", ";", ":", "'"]:
        x = x.replace(ch, " ")
    x = " ".join(x.split())
    return x

In [24]:
f6_be_functional['city_of_facility']=f6_be_functional['city_of_facility'].map(normalize_text)

In [25]:
f6_be_functional.head()

,reportingyear,parent_facilityinspireid,installationinspireid,city_of_facility,longitude,latitude
0,2023,BE.WA/297010000.FACILITY,BE.WA/297010100.INSTALLATION,comines warneton,3.001007,50.802185
1,2023,BE.WA/099010000.FACILITY,BE.WA/099010100.INSTALLATION,leuze en hainaut,3.632182,50.604042
2,2023,BE.WA/240010000.FACILITY,BE.WA/240010100.INSTALLATION,NaN,3.868725,50.458390
3,2023,BE.WA/010010000.FACILITY,BE.WA/010010400.INSTALLATION,vielsalm,5.956051,50.291027
4,2021,BE.WA/130010000.FACILITY,BE.WA/130010100.INSTALLATION,mouscron,3.251511,50.745190

In [26]:
f6_be_functional.isnull().sum()

reportingyear                 0
parent_facilityinspireid      0
installationinspireid         0
city_of_facility            157
longitude                     0
latitude                      0
dtype: int64

In [28]:
f6_be_functional=f6_be_functional.fillna(value={'city_of_facility':'unknown'})

In [29]:
f6_be_functional.isnull().sum()

reportingyear               0
parent_facilityinspireid    0
installationinspireid       0
city_of_facility            0
longitude                   0
latitude                    0
dtype: int64

In [31]:
len(f6_be_functional['installationinspireid'].max())

103

In [33]:
len(f6_be_functional['city_of_facility'].max())

11